S=str(input('Introduceti sirul'))
print('a)' , S.count('A'))
print('b)' , S.replace('A', '*'))
print('c)' , S.replace('B', ' '))
print('d)' , S.count('MA'))
print('e)' , S.replace('MA', 'TA'))
print('f)' , S.replace('TO', ' '))
print('h)' , S[::-1])